export {default as  PhotoHader }  from './PhotoHader'
export {default as  AccProducts }  from './acceuilproduits'
export {default as  AcceuilBanner }  from './AcceuilBanner'
export {default as  CardsBlocks }  from './CardsBlocks'
export {default as  ContactForm }  from './ContactForm'
export {default as  Footer }  from './Footer'
export {default as  NavBar }  from './NavBar'
export {default as  Realisations }  from './Realisations'
export {default as  AboutMagasin }  from './AboutMagasin'
export {default as Haderproduit} from './haderproduit'
export {default as Cardproduct} from './Cardproduct'
export {default as SidebarProduit } from './sidebarProduit'